spring:
  application:
    name: spring-boot-oracle-soda


oracle:
  datasource:
    username: ${ORACLE_USERNAME:sys as sysdba}
    password: ${ORACLE_PASSWORD:password}
    url: ${ORACLE_URL:jdbc:oracle:thin:@//localhost:1521/o18c3}
  soda:
    collection: ${ORACLE_COLLECTION:Employee}
