spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_service
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true